include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/**.g.dart'

linter:
  rules:
    flutter_style_todos: false
    sort_constructors_first: false
    cascade_invocations: false
    public_member_api_docs: false
