name: color_palette_formats
description: A Flutter package for decoding and encoding various color palette formats
version: 1.1.1
repository: https://github.com/albemala/color_palette_formats

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  buffer: ^1.2.2
  archive: ^3.4.10

  dart_mappable: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.1

  very_good_analysis: ^5.1.0

flutter:
