name: palettes
description: A new Flutter package project.
version: 1.0.0
repository: https://github.com/albemala/flutter_palettes

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  buffer: ^1.1.1
  archive: ^3.3.1

  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0

  very_good_analysis: ^3.1.0

flutter:
