name: color_palette_formats
description: A Flutter package for decoding and encoding various color palette formats
version: 2.0.2
repository: https://github.com/albemala/color_palette_formats

funding:
  - https://github.com/sponsors/albemala
  - https://www.buymeacoffee.com/albemala

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.9.0
  buffer: ^1.2.3
  archive: ^4.0.2

  dart_mappable: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0

  very_good_analysis: ^7.0.0

flutter: